# Use this docker-compose to test the algorithm locally
services:
  algorithm:
    build: .
    volumes:
      - ./_data/inputs:/data/inputs:ro
      - ./_data/ddos:/data/ddos:ro
      - ./_data/outputs:/data/outputs:rw
      - ./_data/logs:/data/logs:rw
      - ./algorithm/src:/algorithm/src/
      - ./algorithm/tests:/algorithm/tests/
      - ./entrypoint.sh:/algorithm/entrypoint.sh
    environment:
      DEV: 1
      # TEST: 1
      DIDS: '["sample_input"]'
      secret: "1234"
      TRANSFORMATION_DID: "1234"
